http:
  routers:
    adguard-rtr:
      entryPoints:
        - http
        - https
      middlewares:
        - adguard-add-admin
      rule: "HostHeader(`adguard.sonofborge.com`)"
      service: adguard-svc
      tls:
        certResolver: dns-cloudflare
  middlewares:
    adguard-add-admin:
      addPrefix:
        prefix: "/login.html"
  services:
    adguard-svc:
      loadBalancer:
        servers:
          - url: "http://192.168.1.121:80"
