http:
  routers:
    adguard:
      entryPoints:
        - https
      rule: "Host(`adguard.{{ env "DOMAIN_NAME" }}`)"
      service: adguard
      tls:
  services:
    adguard:
      loadBalancer:
        servers:
          - url: `http.{{ env "ADGUARD_IP" }}:{{ env "ADGUARD_PORT" }}`
