http:
  routers:
    adguard:
      entryPoints:
        - https
      middlewares:
        - adguard-add-admin
      rule: "HostHeader(`adguard.sonofborge.com`)"
      service: adguard
      tls:
        certResolver: dns-cloudflare
  middlewares:
    adguard-add-admin:
      addPrefix:
        prefix: "/login.html"
  services:
    adguard:
      loadBalancer:
        servers:
          - url: "http://192.168.1.121:80"
