http:
  routers:
    unifi-rtr:
      entryPoints:
        - https
      middlewares:
        - chain-authelia
      rule: "Host(`unifi.{{ env "DOMAIN_NAME" }}`)"
      service: unifi-svc
      tls:
  services:
    unifi-svc:
      loadBalancer:
        servers:
          - url: "http://{{ env "UNIFI_IP" }}:{{ env "UNIFI_PORT" }}"
