http:
  routers:
    portainer-rtr:
      entryPoints:
        - https
      middlewares:
        - chain-authelia
      rule: "Host(`portainer.{{ env "DOMAIN_NAME" }}`)"
      service: portainer-svc
  services:
    portainer-svc:
      loadBalancer:
        servers:
          url: "http://127.0.0.1:9000"
