http:
  routers:
    adguard:
      entryPoints:
        - https
      rule: "Host(`adguard.{{ env DOMAIN_NAME }}`)"
      service: adguard
      tls:
        certResolver: dns-cloudflare
  services:
    adguard:
      loadBalancer:
        servers:
          - url: "http://192.168.1.121:80"
