http:
  routers:
    unifi-rtr:
      entryPoints:
        - https
      middlewares:
        - chain-authelia
      rule: "Host(`unifi.{{ env "DOMAIN_NAME" }}`)"
      service: unifi-svc
      tls:
        certResolver: dns-cloudflare
  services:
    unifi-svc:
      loadBalancer:
        passHostHeader: true
        servers:
          - address: "https://{{ env "UNIFI_IP" }}:{{ env "UNIFI_PORT" }}"
